openapi: 3.0.0
info:
  title: RAG Chatbot API with Neon DB Integration
  description: API for the RAG chatbot with integrated Neon structured knowledge
  version: 1.0.0
paths:
  /query:
    post:
      summary: Query the RAG chatbot with integrated knowledge sources
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's query
          example: "What is module 2 about?"
        include_context:
          type: boolean
          description: Whether to include context in response
          default: true
        selected_text:
          type: string
          description: User-selected text context (highest priority)
          example: "Physical AI & Humanoid Robotics: An Introduction"
        debug_context:
          type: boolean
          description: Include routing trace for debugging
          default: false
    QueryResponse:
      type: object
      required:
        - response
        - context_used
        - context_source
      properties:
        response:
          type: string
          description: The agent's response to the query
          example: "Module 2 covers the fundamentals of Physical AI..."
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
          description: List of sources used in the response
        query_type:
          type: string
          enum: [book-related, general]
          description: Type of query processed
        context_used:
          type: boolean
          description: Whether context was used in the response
        context_source:
          type: string
          enum: [user, neon, qdrant, general]
          description: Primary source of context used
        confidence:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Confidence level in the response (when context used)
          example: 0.85
        debug_info:
          type: object
          description: Debug information when debug_context=true
          properties:
            routing_trace:
              type: string
              description: Trace of how the query was routed
            neon_query_time:
              type: number
              format: float
              description: Time taken for Neon DB query (ms)
            qdrant_query_time:
              type: number
              format: float
              description: Time taken for Qdrant query (ms)
    Source:
      type: object
      required:
        - url
        - title
        - content
        - score
      properties:
        url:
          type: string
          description: URL of the source
          example: "https://example.com/chapter2"
        title:
          type: string
          description: Title of the source
          example: "Module 2: Physical AI Fundamentals"
        content:
          type: string
          description: Content of the source
          example: "Physical AI combines traditional AI with embodied intelligence..."
        score:
          type: number
          format: float
          description: Relevance score
          example: 0.85
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid query format"
        details:
          type: string
          description: Additional error details